/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIdRouteImport } from './routes/test.$id'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdRoute = TestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/tests': typeof TestsRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/tests': typeof TestsRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/tests': typeof TestsRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/tests' | '/test/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/tests' | '/test/$id'
  id: '__root__' | '/' | '/new' | '/tests' | '/test/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  TestsRoute: typeof TestsRoute
  TestIdRoute: typeof TestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id': {
      id: '/test/$id'
      path: '/test/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof TestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  TestsRoute: TestsRoute,
  TestIdRoute: TestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
